### PR TITLE
Optimize building the reply chain

### PR DESCRIPTION
**Pull request by 2048khz-gachi-rmx**
Instead of making an API request for every reply, we try to use the built-in cache or at least fetch the history to build replies in bulk

+90000% performance boost ong fr fr

### CODE REVIEW

**Comment by rwf93** [comment]
I read ``+90000% performance boost ong fr fr`` and said :)
LTGM!!!!!

**Comment by 2048khz-gachi-rmx** [comment]
> LTGM

ltgsmall

**Comment by rwf93** [comment]
You should squash your commits... NOW!

**Comment by 2048khz-gachi-rmx** [comment]
[be careful what you wish for,,,,,,,,,,,,,,](https://github.com/Kodakoba/Gcode/pull/3)

**Pull request merged**
